server.port=${PORT:8080}

# PostgreSQL - Render
spring.datasource.url=jdbc:postgresql://dpg-d8cas9reo5us73epigo0-a/cobro_db
spring.datasource.username=cobro_db_user
spring.datasource.password=O7aqj19nLOVx0out02NqJ8TswKKGGYns
spring.datasource.driver-class-name=org.postgresql.Driver

# H2 Console deshabilitada en producción
spring.h2.console.enabled=false

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# CORS
allowed.origins=${ALLOWED_ORIGINS:http://localhost:4200}
