services:
  - type: web
    name: cobro-backend
    runtime: docker
    dockerfilePath: ./backend/cobro/Dockerfile
    dockerContext: ./backend/cobro
    plan: free
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: ALLOWED_ORIGINS
        value: https://*.vercel.app,http://localhost:4200
